# Generated by Django 5.0.1 on 2024-01-23 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_processor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clusterdata",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="clusterdata",
            name="ratios",
        ),
    ]
