# Generated by Django 5.0.1 on 2024-01-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processor", "0002_remove_clusterdata_colors_remove_clusterdata_ratios"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterdata",
            name="colors",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clusterdata",
            name="ratios",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
