version: "3.9"

services:
    django:
        image: 663524913446.dkr.ecr.us-east-2.amazonaws.com/palette-pal-backend-image:1.31
        ports:
            - "8000:8000"
        command: >
            sh -c "python manage.py collectstatic --noinput &&
                   gunicorn server.wsgi:application --bind 0.0.0.0:8000"
